#!/bin/sh
# $INTERFACE == uci if name
# $ACTION == action
# $DEVICE == device if name
[ ifup = "$ACTION" ] && {
		LogFile="/dev/null"
        if echo "$INTERFACE" | grep "nox_ovpn_[0-9]*" > /dev/null
		then
			InstanceId=$(echo "$INTERFACE" | sed 's|nox_ovpn_||1')
			IpAddr=$(ifconfig nox_ovpn_$InstanceId | grep -o "inet addr:[^ ]*" | sed 's|.*:||1')
			ifconfig nox_ovpn_$InstanceId >> $LogFile
			echo $IpAddr >> $LogFile
			ip route add default via "$IpAddr" table nox_$InstanceId  >> &2>1 $LogFile
		fi
		echo "$ACTION == $INTERFACE == $DEVICE" >> $LogFile
}

